package main

var typesTmpl = `
{{define "SimpleType"}}
	{{$name := replaceReservedWords .Name}}
	type {{$name}} {{toGoType .Restriction.Base}}
	const (
		{{with .Restriction}}
			{{range .Enumeration}}
				{{$value := replaceReservedWords .Value}}{{$value | makeFieldPublic}} {{$name}} = "{{$value}}" {{end}}
		{{end}}
	)
{{end}}

{{define "ComplexTypeGlobal"}}
	{{$name := replaceReservedWords .Name}}

	type {{$name}} struct {
		{{if ne .ComplexContent.Extension.Base ""}}
			{{$baseType := .ComplexContent.Extension.Base}}
			{{ if $baseType }}
				*{{stripns $baseType}}
			{{end}}

			{{template "Elements" .ComplexContent.Extension.Sequence.Elements}}
		{{ else }}
			{{template "Elements" .Sequence.Elements}}
		{{end}}
	}
{{end}}

{{define "ComplexTypeLocal"}}
	{{$name := replaceReservedWords .Name}}

	{{with .ComplexType}}
		type {{$name}} struct {
			{{if ne .ComplexContent.Extension.Base ""}}
				{{$baseType := .ComplexContent.Extension.Base}}
				{{ if $baseType }}
					*{{stripns $baseType}}
				{{end}}

				{{template "Elements" .ComplexContent.Extension.Sequence.Elements}}
			{{ else }}
				{{template "Elements" .Sequence.Elements}}
			{{end}}
		}
	{{end}}
{{end}}

{{define "Elements"}}
	{{range .}}
		{{replaceReservedWords .Name}} {{if eq .MaxOccurs "unbounded"}}[]{{end}}{{.Type | toGoType}}{{end}}
{{end}}

package main
//Generated by https://github.com/c4milo/gowsdl
//Do not modify
//Copyright (c) 2014, Camilo Aguilar. All rights reserved.
import (
	"encoding/xml"
	//"time"
	{{/*range .Imports*/}}
		{{/*.*/}}
	{{/*end*/}}
)

{{range .Schemas}}
	{{range .SimpleType}}
		{{template "SimpleType" .}}
	{{end}}
	{{range .Elements}}
		{{if not .Type}}
			{{template "ComplexTypeLocal" .}}
		{{end}}
	{{end}}
	{{range .ComplexTypes}}
		{{template "ComplexTypeGlobal" .}}
	{{end}}
{{end}}
`
