// Code generated by gowsdl DO NOT EDIT.

package enedis

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type AcceptabiliteResultatCodeType string

type AcheminementTarifCodeType string

type ActeurCodeType string

type ActiviteCodeNafType string

type ActiviteSecteurCodeType string

type AdresseAfnorLigneType string

type AdresseEmailType string

type AffaireAnnulationMotifCodeType string

type AffaireAnnulationMotifRefusCodeType string

type AffaireClotureMotifCodeType string

type AffaireEtatCodeType string

type AffaireIdType string

type AffaireModificationMotifRefusCodeType string

type AffaireNatureModificationCodeType string

type AffaireStatutCodeType string

const (
	AffaireStatutCodeTypeANNUL AffaireStatutCodeType = "ANNUL"

	AffaireStatutCodeTypeCOURS AffaireStatutCodeType = "COURS"

	AffaireStatutCodeTypeTERMN AffaireStatutCodeType = "TERMN"
)

type AlimentationEtatCodeType string

const (
	AlimentationEtatCodeTypeALIM AlimentationEtatCodeType = "ALIM"

	AlimentationEtatCodeTypeCOUP AlimentationEtatCodeType = "COUP"

	AlimentationEtatCodeTypeLIMI AlimentationEtatCodeType = "LIMI"

	AlimentationEtatCodeTypeNRAC AlimentationEtatCodeType = "NRAC"

	AlimentationEtatCodeTypeNALI AlimentationEtatCodeType = "NALI"
)

type AlimentationModeApresCompteurCodeType string

type AlimentationSecoursModeBasculeCodeType string

type AnneeType soap.GYear

type ApplicationCodeType string

type BooleenType bool

type CalendrierCodeType string

type CalendrierJourTypeCategorieCodeType string

type CalendrierJourTypeCodeType string

type CentreGeographiqueCodeType string

const (
	CentreGeographiqueCodeType11 CentreGeographiqueCodeType = "11"

	CentreGeographiqueCodeType12 CentreGeographiqueCodeType = "12"

	CentreGeographiqueCodeType121 CentreGeographiqueCodeType = "121"

	CentreGeographiqueCodeType122 CentreGeographiqueCodeType = "122"

	CentreGeographiqueCodeType124 CentreGeographiqueCodeType = "124"

	CentreGeographiqueCodeType125 CentreGeographiqueCodeType = "125"

	CentreGeographiqueCodeType13 CentreGeographiqueCodeType = "13"

	CentreGeographiqueCodeType14 CentreGeographiqueCodeType = "14"

	CentreGeographiqueCodeType142 CentreGeographiqueCodeType = "142"

	CentreGeographiqueCodeType143 CentreGeographiqueCodeType = "143"

	CentreGeographiqueCodeType144 CentreGeographiqueCodeType = "144"

	CentreGeographiqueCodeType145 CentreGeographiqueCodeType = "145"

	CentreGeographiqueCodeType146 CentreGeographiqueCodeType = "146"

	CentreGeographiqueCodeType147 CentreGeographiqueCodeType = "147"

	CentreGeographiqueCodeType148 CentreGeographiqueCodeType = "148"

	CentreGeographiqueCodeType15 CentreGeographiqueCodeType = "15"

	CentreGeographiqueCodeType151 CentreGeographiqueCodeType = "151"

	CentreGeographiqueCodeType152 CentreGeographiqueCodeType = "152"

	CentreGeographiqueCodeType154 CentreGeographiqueCodeType = "154"

	CentreGeographiqueCodeType155 CentreGeographiqueCodeType = "155"

	CentreGeographiqueCodeType16 CentreGeographiqueCodeType = "16"

	CentreGeographiqueCodeType161 CentreGeographiqueCodeType = "161"

	CentreGeographiqueCodeType162 CentreGeographiqueCodeType = "162"

	CentreGeographiqueCodeType163 CentreGeographiqueCodeType = "163"

	CentreGeographiqueCodeType164 CentreGeographiqueCodeType = "164"

	CentreGeographiqueCodeType165 CentreGeographiqueCodeType = "165"

	CentreGeographiqueCodeType171 CentreGeographiqueCodeType = "171"

	CentreGeographiqueCodeType172 CentreGeographiqueCodeType = "172"

	CentreGeographiqueCodeType173 CentreGeographiqueCodeType = "173"

	CentreGeographiqueCodeType175 CentreGeographiqueCodeType = "175"

	CentreGeographiqueCodeType176 CentreGeographiqueCodeType = "176"

	CentreGeographiqueCodeType177 CentreGeographiqueCodeType = "177"

	CentreGeographiqueCodeType179 CentreGeographiqueCodeType = "179"

	CentreGeographiqueCodeType191 CentreGeographiqueCodeType = "191"

	CentreGeographiqueCodeType193 CentreGeographiqueCodeType = "193"

	CentreGeographiqueCodeType194 CentreGeographiqueCodeType = "194"

	CentreGeographiqueCodeType195 CentreGeographiqueCodeType = "195"

	CentreGeographiqueCodeType196 CentreGeographiqueCodeType = "196"

	CentreGeographiqueCodeType197 CentreGeographiqueCodeType = "197"

	CentreGeographiqueCodeType198 CentreGeographiqueCodeType = "198"

	CentreGeographiqueCodeType199 CentreGeographiqueCodeType = "199"

	CentreGeographiqueCodeType21 CentreGeographiqueCodeType = "21"

	CentreGeographiqueCodeType211 CentreGeographiqueCodeType = "211"

	CentreGeographiqueCodeType212 CentreGeographiqueCodeType = "212"

	CentreGeographiqueCodeType213 CentreGeographiqueCodeType = "213"

	CentreGeographiqueCodeType214 CentreGeographiqueCodeType = "214"

	CentreGeographiqueCodeType215 CentreGeographiqueCodeType = "215"

	CentreGeographiqueCodeType22 CentreGeographiqueCodeType = "22"

	CentreGeographiqueCodeType221 CentreGeographiqueCodeType = "221"

	CentreGeographiqueCodeType222 CentreGeographiqueCodeType = "222"

	CentreGeographiqueCodeType223 CentreGeographiqueCodeType = "223"

	CentreGeographiqueCodeType224 CentreGeographiqueCodeType = "224"

	CentreGeographiqueCodeType225 CentreGeographiqueCodeType = "225"

	CentreGeographiqueCodeType23 CentreGeographiqueCodeType = "23"

	CentreGeographiqueCodeType231 CentreGeographiqueCodeType = "231"

	CentreGeographiqueCodeType232 CentreGeographiqueCodeType = "232"

	CentreGeographiqueCodeType233 CentreGeographiqueCodeType = "233"

	CentreGeographiqueCodeType234 CentreGeographiqueCodeType = "234"

	CentreGeographiqueCodeType235 CentreGeographiqueCodeType = "235"

	CentreGeographiqueCodeType24 CentreGeographiqueCodeType = "24"

	CentreGeographiqueCodeType241 CentreGeographiqueCodeType = "241"

	CentreGeographiqueCodeType242 CentreGeographiqueCodeType = "242"

	CentreGeographiqueCodeType243 CentreGeographiqueCodeType = "243"

	CentreGeographiqueCodeType245 CentreGeographiqueCodeType = "245"

	CentreGeographiqueCodeType25 CentreGeographiqueCodeType = "25"

	CentreGeographiqueCodeType251 CentreGeographiqueCodeType = "251"

	CentreGeographiqueCodeType252 CentreGeographiqueCodeType = "252"

	CentreGeographiqueCodeType253 CentreGeographiqueCodeType = "253"

	CentreGeographiqueCodeType254 CentreGeographiqueCodeType = "254"

	CentreGeographiqueCodeType256 CentreGeographiqueCodeType = "256"

	CentreGeographiqueCodeType258 CentreGeographiqueCodeType = "258"

	CentreGeographiqueCodeType259 CentreGeographiqueCodeType = "259"

	CentreGeographiqueCodeType26 CentreGeographiqueCodeType = "26"

	CentreGeographiqueCodeType41 CentreGeographiqueCodeType = "41"

	CentreGeographiqueCodeType42 CentreGeographiqueCodeType = "42"

	CentreGeographiqueCodeType43 CentreGeographiqueCodeType = "43"

	CentreGeographiqueCodeType45 CentreGeographiqueCodeType = "45"

	CentreGeographiqueCodeType51 CentreGeographiqueCodeType = "51"

	CentreGeographiqueCodeType52 CentreGeographiqueCodeType = "52"

	CentreGeographiqueCodeType54 CentreGeographiqueCodeType = "54"

	CentreGeographiqueCodeType55 CentreGeographiqueCodeType = "55"

	CentreGeographiqueCodeType56 CentreGeographiqueCodeType = "56"

	CentreGeographiqueCodeType63 CentreGeographiqueCodeType = "63"

	CentreGeographiqueCodeType64 CentreGeographiqueCodeType = "64"

	CentreGeographiqueCodeType65 CentreGeographiqueCodeType = "65"

	CentreGeographiqueCodeType71 CentreGeographiqueCodeType = "71"

	CentreGeographiqueCodeType72 CentreGeographiqueCodeType = "72"

	CentreGeographiqueCodeType73 CentreGeographiqueCodeType = "73"

	CentreGeographiqueCodeType74 CentreGeographiqueCodeType = "74"

	CentreGeographiqueCodeType75 CentreGeographiqueCodeType = "75"

	CentreGeographiqueCodeType91 CentreGeographiqueCodeType = "91"

	CentreGeographiqueCodeType92 CentreGeographiqueCodeType = "92"

	CentreGeographiqueCodeType93 CentreGeographiqueCodeType = "93"

	CentreGeographiqueCodeType94 CentreGeographiqueCodeType = "94"

	CentreGeographiqueCodeType95 CentreGeographiqueCodeType = "95"

	CentreGeographiqueCodeType96 CentreGeographiqueCodeType = "96"

	CentreGeographiqueCodeType97 CentreGeographiqueCodeType = "97"
)

type Chaine15Type string

type Chaine2047Type string

type Chaine255Type string

type CircuitTempoCodeType string

type CiviliteAbreviationType string

type ClasseTemporelleCodeType string

type CleTeleAccesType string

type ClientFinalCategorieCodeType string

const (
	ClientFinalCategorieCodeTypePRO ClientFinalCategorieCodeType = "PRO"

	ClientFinalCategorieCodeTypeRES ClientFinalCategorieCodeType = "RES"
)

type ClientPrioritaireTypeCodeType string

type CodeEicType string

type CodePostalFrancaisType string

type CommuneFranceCodeInseeType string

type CompteurIntensiteNominaleCodeType string

type CompteurModeleSousTypeCodeType string

type CompteurTensionNominaleCodeType string

type CompteurTypeCodeType string

type ConsommationTypeCodeType string

const (
	ConsommationTypeCodeTypeFACTU ConsommationTypeCodeType = "FACTU"

	ConsommationTypeCodeTypeMOYEN ConsommationTypeCodeType = "MOYEN"
)

type ConsuelMotifNonExigibiliteCodeType string

type ContratIdType string

type CoupureLocalisationCodeType string

type CoupureMotifCodeType string

type CourrierIdType string

type CourrierModeleCodeType string

type CourrierMotifNonDistributionCodeType string

type CourrierStatutCodeType string

type CourrierTypeCodeType string

type CreneauHoraireCodeType string

type DateHeureType soap.XSDDateTime

type DateType soap.XSDDate

type DemandeChangementFrnCorrectifMotifCodeType string

type DemandeCommunicationDistributeurTypeCodeType string

type DemandeDiverseComptageTypeCodeType string

type DemandeDiverseInformationsTypeCodeType string

type DemandeDiverseQualiteFournitureTypeCodeType string

type DemandeDiverseReseauTypeCodeType string

type DemandeMediaCodeType string

type DemandeMiseEnServiceCorrectifMotifCodeType string

type DemandeObjetCodeType string

type DemandeTechniqueTypeCodeType string

type DeviseAbreviationType string

type DisjoncteurCalibreCodeType string

type DisjoncteurNatureCodeType string

type DispositifComptageParticulariteCodeType string

type DispositifParticulierLimitationPerturbationsCodeType string

type DomaineTensionCodeType string

const (
	DomaineTensionCodeTypeBTINF DomaineTensionCodeType = "BTINF"

	DomaineTensionCodeTypeBTSUP DomaineTensionCodeType = "BTSUP"

	DomaineTensionCodeTypeHTA DomaineTensionCodeType = "HTA"

	DomaineTensionCodeTypeHTB DomaineTensionCodeType = "HTB"
)

type DureeUniteSymboleType string

const (
	DureeUniteSymboleTypeAnnee DureeUniteSymboleType = "annee"

	DureeUniteSymboleTypeH DureeUniteSymboleType = "h"

	DureeUniteSymboleTypeJour DureeUniteSymboleType = "jour"

	DureeUniteSymboleTypeMin DureeUniteSymboleType = "min"

	DureeUniteSymboleTypeMois DureeUniteSymboleType = "mois"

	DureeUniteSymboleTypeMs DureeUniteSymboleType = "ms"

	DureeUniteSymboleTypeS DureeUniteSymboleType = "s"

	DureeUniteSymboleTypeSemaine DureeUniteSymboleType = "semaine"
)

type DysfonctionnementNatureCodeType string

type EquipementElectriqueLocalisationCodeType string

type EquipementElectriqueRegimeProprieteCodeType string

type EtablissementNumSiretType string

type FaisabiliteMotifImpossibiliteCodeType string

type FaisabiliteReserveMotifCodeType string

type FichierIdType string

type FichierNomType string

type FinaliteCodeType string

type FraisCodeType string

type FraudeNatureCodeType string

type FraudeOuDysfonctionnementMethodeCalculCodeType string

type FraudeOuDysfonctionnementMethodeFacturationCodeType string

type GrandeurMetierCodeType string

type GrandeurPhysiqueCodeType string

type GroupePeriodeMobileCodeType string

type HeureType soap.XSDTime

type IndexUniteSymboleType string

type IntensiteUniteSymboleType string

const (
	IntensiteUniteSymboleTypeA IntensiteUniteSymboleType = "A"

	IntensiteUniteSymboleTypeMA IntensiteUniteSymboleType = "mA"
)

type IntervenantTypeCodeType string

type InterventionDemandeMotifRefusCodeType string

type InterventionDeplanificationMotifCodeType string

type InterventionEtatCodeType string

const (
	InterventionEtatCodeTypeANNUL InterventionEtatCodeType = "ANNUL"

	InterventionEtatCodeTypeCLOS InterventionEtatCodeType = "CLOS"

	InterventionEtatCodeTypeDMND InterventionEtatCodeType = "DMND"

	InterventionEtatCodeTypePLAN InterventionEtatCodeType = "PLAN"
)

type InterventionNonRealisationMotifCodeType string

type InterventionPeriodeTypeCodeType string

const (
	InterventionPeriodeTypeCodeTypeHEOE InterventionPeriodeTypeCodeType = "HEOE"

	InterventionPeriodeTypeCodeTypeHHOE InterventionPeriodeTypeCodeType = "HHOE"

	InterventionPeriodeTypeCodeTypeHHOS InterventionPeriodeTypeCodeType = "HHOS"

	InterventionPeriodeTypeCodeTypeHHOW InterventionPeriodeTypeCodeType = "HHOW"

	InterventionPeriodeTypeCodeTypeHHSW InterventionPeriodeTypeCodeType = "HHSW"
)

type InterventionPlanificationHorsDelaiMotifCodeType string

type InterventionRealisationEtatCodeType string

const (
	InterventionRealisationEtatCodeTypeNREA InterventionRealisationEtatCodeType = "NREA"

	InterventionRealisationEtatCodeTypePREA InterventionRealisationEtatCodeType = "PREA"

	InterventionRealisationEtatCodeTypeREAL InterventionRealisationEtatCodeType = "REAL"
)

type InterventionReplanificationMotifCodeType string

type JourDuMoisType soap.GDay

type LibelleAffichageCompteurType string

type LigneTelephoniqueNumType string

type LimiteurTypeCodeType string

type LongueurUniteSymboleType string

const (
	LongueurUniteSymboleTypeKm LongueurUniteSymboleType = "km"

	LongueurUniteSymboleTypeM LongueurUniteSymboleType = "m"
)

type MesureDeclencheurCodeType string

type MesureNatureCodeType string

type MesureOrigineCodeType string

type MesureStatutCodeType string

type MesureTypeCodeType string

type MesureUniteSymboleType string

type MoisEtJourType soap.GMonthDay

type MoisType soap.GMonth

type NbDecimalType float64

type NbEntierStrictementPositifType uint32

type NbEntierType int32

type NiveauOuvertureServicesCodeType string

type NonPriseEnCompteAutoreleveMotifCodeType string

type OffreTypeCodeType string

const (
	OffreTypeCodeTypeNO OffreTypeCodeType = "NO"

	OffreTypeCodeTypeOH OffreTypeCodeType = "OH"
)

type OperationCodeType string

type OptionBilanContinuiteFournitureCoupureTypeCodeType string

type OptionBilanContinuiteFournitureTypeCodeType string

type OptionContractuelleSouscriteIdType string

type PeriodiciteCodeType string

type PersonneMoraleNumSirenType string

type PlageHeuresCreusesCodeType string

type PointAppartenanceRegroupementHebergeurDecomptantCodeType string

const (
	PointAppartenanceRegroupementHebergeurDecomptantCodeTypeDECO PointAppartenanceRegroupementHebergeurDecomptantCodeType = "DECO"

	PointAppartenanceRegroupementHebergeurDecomptantCodeTypeHEBE PointAppartenanceRegroupementHebergeurDecomptantCodeType = "HEBE"

	PointAppartenanceRegroupementHebergeurDecomptantCodeTypeNON PointAppartenanceRegroupementHebergeurDecomptantCodeType = "NON"
)

type PointAppartenanceRegroupementTurpeCodeType string

const (
	PointAppartenanceRegroupementTurpeCodeTypeNON PointAppartenanceRegroupementTurpeCodeType = "NON"

	PointAppartenanceRegroupementTurpeCodeTypeREGT PointAppartenanceRegroupementTurpeCodeType = "REGT"

	PointAppartenanceRegroupementTurpeCodeTypeRGPT PointAppartenanceRegroupementTurpeCodeType = "RGPT"
)

type PointEtatContractuelCodeType string

const (
	PointEtatContractuelCodeTypeECRAC PointEtatContractuelCodeType = "ECRAC"

	PointEtatContractuelCodeTypeINACCE PointEtatContractuelCodeType = "INACCE"

	PointEtatContractuelCodeTypeECRES PointEtatContractuelCodeType = "ECRES"

	PointEtatContractuelCodeTypeIMPRO PointEtatContractuelCodeType = "IMPRO"

	PointEtatContractuelCodeTypeRESIL PointEtatContractuelCodeType = "RESIL"

	PointEtatContractuelCodeTypeSERVC PointEtatContractuelCodeType = "SERVC"
)

type PointIdType string

type PointSegmentClienteleCodeType string

const (
	PointSegmentClienteleCodeTypeC1 PointSegmentClienteleCodeType = "C1"

	PointSegmentClienteleCodeTypeC2 PointSegmentClienteleCodeType = "C2"

	PointSegmentClienteleCodeTypeC3 PointSegmentClienteleCodeType = "C3"

	PointSegmentClienteleCodeTypeC4 PointSegmentClienteleCodeType = "C4"

	PointSegmentClienteleCodeTypeC5 PointSegmentClienteleCodeType = "C5"

	PointSegmentClienteleCodeTypeINDET PointSegmentClienteleCodeType = "INDET"
)

type PosteHoraireCodeType string

type PrejudiceNatureCodeType string

type PrestationCasCodeType string

type PrestationEnvisageeCodeType string

const (
	PrestationEnvisageeCodeTypeCFN PrestationEnvisageeCodeType = "CFN"

	PrestationEnvisageeCodeTypeMES PrestationEnvisageeCodeType = "MES"
)

type PrestationFicheCodeType string

type PrestationMotifNonFacturationCodeType string

type PrestationMotifNonRealisationCodeType string

type PrestationOptionCodeType string

type ProductionAutonomeCouplageModeCodeType string

type ProgrammeCircuitChauffageTempoCodeType string

type ProgrammeCircuitEauTempoCodeType string

type PuissanceUniteSymboleType string

const (
	PuissanceUniteSymboleTypeKVA PuissanceUniteSymboleType = "kVA"

	PuissanceUniteSymboleTypeKVAR PuissanceUniteSymboleType = "kVAR"

	PuissanceUniteSymboleTypeKW PuissanceUniteSymboleType = "kW"
)

type RattachementIdType string

type RattachementPointRoleCodeType string

type RattachementTypeCodeType string

type RecevabiliteMotifRefusCodeType string

type RecevabilitePremiereMiseEnServicePourEssaiMotifCodeType string

type RecevabiliteResultatCodeType string

type ReclamationSousTypeCodeType string

type ReclamationTypeCodeType string

type RectificationMotifCodeType string

type RefCompteurType string

type RelaisCommandeTypeCodeType string

type RelaisNatureCodeType string

type ReleveMediaCodeType string

type ReleveModeCodeType string

type RelevePlageCodeType string

type ReleveQualificationCodeType string

type ReleveTraitementModeCodeType string

type ResidenceTypeCodeType string

const (
	ResidenceTypeCodeTypePRP ResidenceTypeCodeType = "PRP"

	ResidenceTypeCodeTypeSEC ResidenceTypeCodeType = "SEC"
)

type SecteurGeographiqueCodeType string

type SituationContractuelleGestionModeCodeType string

const (
	SituationContractuelleGestionModeCodeTypeINT SituationContractuelleGestionModeCodeType = "INT"

	SituationContractuelleGestionModeCodeTypeGRD SituationContractuelleGestionModeCodeType = "GRD"
)

type StructureComptageCodeType string

type StructureTarifaireContexteUtilisationCodeType string

type TensionLivraisonCodeType string

type TensionUniteSymboleType string

const (
	TensionUniteSymboleTypeKV TensionUniteSymboleType = "kV"

	TensionUniteSymboleTypeV TensionUniteSymboleType = "V"
)

type TourneeCodeType string

type TransformateurCalibreCodeType string

type TransformateurCouplageTypeCodeType string

type TransformateurCourantPositionCodeType string

type TransformateurPrecisionClasseCodeType string

type UsageChantierCodeType string

type UtilisateurLoginType string

type ZoneQualiteDesserteCodeType string

type AcceptabiliteResultatType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *AcceptabiliteResultatCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type AcheminementTarifType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *AcheminementTarifCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ActiviteSecteurType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ActiviteSecteurCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ActiviteType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ActiviteCodeNafType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type AdresseAfnorType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc adresseInstallationNormalisee"`

	Ligne1 *AdresseAfnorLigneType `xml:"ligne1,omitempty" json:"ligne1,omitempty"`

	Ligne2 *AdresseAfnorLigneType `xml:"ligne2,omitempty" json:"ligne2,omitempty"`

	Ligne3 *AdresseAfnorLigneType `xml:"ligne3,omitempty" json:"ligne3,omitempty"`

	Ligne4 *AdresseAfnorLigneType `xml:"ligne4,omitempty" json:"ligne4,omitempty"`

	Ligne5 *AdresseAfnorLigneType `xml:"ligne5,omitempty" json:"ligne5,omitempty"`

	Ligne6 *AdresseAfnorLigneType `xml:"ligne6,omitempty" json:"ligne6,omitempty"`

	Ligne7 *AdresseAfnorLigneType `xml:"ligne7,omitempty" json:"ligne7,omitempty"`
}

type AffaireAnnulationMotifRefusType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *AffaireAnnulationMotifRefusCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type AffaireAnnulationMotifType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *AffaireAnnulationMotifCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type AffaireClotureMotifType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *AffaireClotureMotifCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type AffaireEtatType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *AffaireEtatCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type AffaireModificationMotifRefusType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *AffaireModificationMotifRefusCodeType `xml:"code,omitempty" json:"code,omitempty"`
}

type AffaireNatureModificationType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *AffaireNatureModificationCodeType `xml:"code,omitempty" json:"code,omitempty"`
}

type AffaireStatutType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *AffaireStatutCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type AlimentationEtatType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *AlimentationEtatCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type AlimentationModeApresCompteurType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *AlimentationModeApresCompteurCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type AlimentationSecoursModeBasculeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *AlimentationSecoursModeBasculeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ApplicationType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ApplicationCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type BilanContinuiteFournitureCoupureTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *OptionBilanContinuiteFournitureCoupureTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type BilanContinuiteFournitureTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *OptionBilanContinuiteFournitureTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type CalendrierType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *CalendrierCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type CentreGeographiqueType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *CentreGeographiqueCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type CircuitTempoType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *CircuitTempoCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ClasseTemporelleType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ClasseTemporelleCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ClientFinalCategorieType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ClientFinalCategorieCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ClientPrioritaireTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ClientPrioritaireTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type CommuneFranceType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *CommuneFranceCodeInseeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type CompteurIntensiteNominaleType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *CompteurIntensiteNominaleCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type CompteurSousTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *CompteurModeleSousTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type CompteurTensionNominaleType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *CompteurTensionNominaleCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ConsommationTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ConsommationTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ConsuelMotifNonExigibiliteType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ConsuelMotifNonExigibiliteCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type CoordonnesGpsType struct {
	Latitude *NbDecimalType `xml:"latitude,omitempty" json:"latitude,omitempty"`

	Longitude *NbDecimalType `xml:"longitude,omitempty" json:"longitude,omitempty"`
}

type CoupureLocalisationType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *CoupureLocalisationCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type CoupureMotifType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *CoupureMotifCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type CourrierModeleType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *CourrierModeleCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type CreneauHoraireType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *CreneauHoraireCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DemandeChangementFrnCorrectifMotifType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DemandeChangementFrnCorrectifMotifCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DemandeCommunicationDistributeurTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DemandeCommunicationDistributeurTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DemandeDiverseComptageTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DemandeDiverseComptageTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DemandeDiverseInformationsTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DemandeDiverseInformationsTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DemandeDiverseQualiteFournitureTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DemandeDiverseQualiteFournitureTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DemandeDiverseReseauTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DemandeDiverseReseauTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DemandeMediaType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DemandeMediaCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DemandeMiseEnServiceCorrectiveMotifType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DemandeMiseEnServiceCorrectifMotifCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DemandeObjetType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DemandeObjetCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DemandeTechniqueTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DemandeTechniqueTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DisjoncteurCalibreType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DisjoncteurCalibreCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DisjoncteurNatureType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DisjoncteurNatureCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DispositifComptageParticulariteType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DispositifComptageParticulariteCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DispositifParticulierLimitationPerturbationsType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DispositifParticulierLimitationPerturbationsCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DomaineTensionType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DomaineTensionCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type DureeType struct {
	Valeur *NbDecimalType `xml:"valeur,omitempty" json:"valeur,omitempty"`

	Unite *DureeUniteSymboleType `xml:"unite,omitempty" json:"unite,omitempty"`
}

type DysfonctionnementNatureType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *DysfonctionnementNatureCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type EquipementElectriqueLocalisationType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *EquipementElectriqueLocalisationCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type EquipementElectriqueRegimeProprieteType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *EquipementElectriqueRegimeProprieteCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type FaisabiliteMotifImpossibiliteType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *FaisabiliteMotifImpossibiliteCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type FaisabiliteReserveMotifType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *FaisabiliteReserveMotifCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type FaisabiliteResultatType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *BooleenType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type FinaliteType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *FinaliteCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type FraisType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc frais"`

	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *FraisCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type FraudeNatureType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *FraudeNatureCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type FraudeOuDysfonctionnementMethodeCalculType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *FraudeOuDysfonctionnementMethodeCalculCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type FraudeOuDysfonctionnementnMethodeFacturationType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *FraudeOuDysfonctionnementMethodeFacturationCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type GeneriqueType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *Chaine15Type `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type GrandeurPhysiqueType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *GrandeurPhysiqueCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type GroupePeriodeMobileType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *GroupePeriodeMobileCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type IntensiteType struct {
	Valeur *NbDecimalType `xml:"valeur,omitempty" json:"valeur,omitempty"`

	Unite *IntensiteUniteSymboleType `xml:"unite,omitempty" json:"unite,omitempty"`
}

type IntervenantTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *IntervenantTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type InterventionDemandeMotifRefusType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *InterventionDemandeMotifRefusCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type InterventionDeplanificationMotifType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *InterventionDeplanificationMotifCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type InterventionEtatType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *InterventionEtatCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type InterventionNonRealisationMotifType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *InterventionNonRealisationMotifCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type InterventionPeriodeTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *InterventionPeriodeTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type InterventionPlanificationHorsDelaiMotifType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *InterventionPlanificationHorsDelaiMotifCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type InterventionRealisationEtatType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *InterventionRealisationEtatCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type InterventionReplanificationMotifType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *InterventionReplanificationMotifCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type LigneFraisType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc ligneFrais"`

	Frais *FraisType `xml:"frais,omitempty" json:"frais,omitempty"`

	Quantite *NbEntierType `xml:"quantite,omitempty" json:"quantite,omitempty"`
}

type LignesFraisType struct {
	LigneFrais *LigneFraisType `xml:"ligneFrais,omitempty" json:"ligneFrais,omitempty"`
}

type LimiteurTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *LimiteurTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type LongueurType struct {
	Valeur *NbDecimalType `xml:"valeur,omitempty" json:"valeur,omitempty"`

	Unite *LongueurUniteSymboleType `xml:"unite,omitempty" json:"unite,omitempty"`
}

type MesureDeclencheurType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *MesureDeclencheurCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type MesureNatureType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *MesureNatureCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type MesureOrigineType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *MesureOrigineCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type MesureStatutType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *MesureStatutCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type MesureTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *MesureTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type MontantType struct {
	Valeur *NbDecimalType `xml:"valeur,omitempty" json:"valeur,omitempty"`

	Unite *DeviseAbreviationType `xml:"unite,omitempty" json:"unite,omitempty"`
}

type NonPriseEnCompteAutoreleveMotifType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *NonPriseEnCompteAutoreleveMotifCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type OffreTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *OffreTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type OperationType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *OperationCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PeriodiciteType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *PeriodiciteCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PlageHeuresCreusesType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *PlageHeuresCreusesCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PointAppartenanceRegroupementHebergeurDecomptantType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *PointAppartenanceRegroupementHebergeurDecomptantCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PointAppartenanceRegroupementTurpeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *PointAppartenanceRegroupementTurpeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PointEtatContractuelType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc etatContractuel"`

	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *PointEtatContractuelCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PointSegmentClienteleType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *PointSegmentClienteleCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PrejudiceNatureType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *PrejudiceNatureCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PrestationCasType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *PrestationCasCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PrestationFacturationType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *BooleenType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PrestationFicheType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *PrestationFicheCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PrestationMotifNonFacturationType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *PrestationMotifNonFacturationCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PrestationMotifNonRealisationType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *PrestationMotifNonRealisationCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PrestationOptionType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *PrestationOptionCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PrestationRealisationType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *BooleenType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ProductionAutonomeCouplageModeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ProductionAutonomeCouplageModeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ProgrammeCircuitChauffageTempoType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ProgrammeCircuitChauffageTempoCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ProgrammeCircuitEauTempoType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ProgrammeCircuitEauTempoCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type PuissanceType struct {
	Valeur *NbDecimalType `xml:"valeur,omitempty" json:"valeur,omitempty"`

	Unite *PuissanceUniteSymboleType `xml:"unite,omitempty" json:"unite,omitempty"`
}

type RattachementPointRoleType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *RattachementPointRoleCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type RattachementTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *RattachementTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type RecevabiliteMotifRefusType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *RecevabiliteMotifRefusCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type RecevabilitePremiereMiseEnServicePourEssaiMotifType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *RecevabilitePremiereMiseEnServicePourEssaiMotifCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type RecevabiliteResultatType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *RecevabiliteResultatCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ReclamationSousTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ReclamationSousTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ReclamationTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ReclamationTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type RectificationMotifType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *RectificationMotifCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type RelaisCommandeTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *RelaisCommandeTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type RelaisNatureType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *RelaisNatureCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ReleveMediaType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ReleveMediaCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ReleveModeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ReleveModeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type RelevePlageType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *RelevePlageCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ReleveQualificationType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ReleveQualificationCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ReleveTraitementModeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ReleveTraitementModeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ResidenceTypeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ResidenceTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type SecteurGeographiqueType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *SecteurGeographiqueCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type SituationContractuelleGestionModeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *SituationContractuelleGestionModeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type StructureComptageType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc typeComptage"`

	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *StructureComptageCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type StructureTarifaireContexteUtilisationType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *StructureTarifaireContexteUtilisationCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type TensionLivraisonType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *TensionLivraisonCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type TensionType struct {
	Valeur *NbDecimalType `xml:"valeur,omitempty" json:"valeur,omitempty"`

	Unite *TensionUniteSymboleType `xml:"unite,omitempty" json:"unite,omitempty"`
}

type TourneeType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *TourneeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type TransformateurCalibreType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *TransformateurCalibreCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type TransformateurCouplageType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *TransformateurCouplageTypeCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type TransformateurCourantPositionType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *TransformateurCourantPositionCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type TransformateurPrecisionClasseType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *TransformateurPrecisionClasseCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type UsageChantierType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *UsageChantierCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type ZoneQualiteDesserteType struct {
	Libelle *Chaine255Type `xml:"libelle,omitempty" json:"libelle,omitempty"`

	Code *ZoneQualiteDesserteCodeType `xml:"http://www.enedis.fr/sge/b2b/dictionnaire/v5.0/dc code,attr,omitempty" json:"code,omitempty"`
}

type RechercherPoint RechercherPointType

type RechercherPointResponse RechercherPointResponseType

type RechercherPointType struct {
	XMLName xml.Name `xml:"ns0:rechercherPoint"`
	XmlNS string `xml:"xmlns:ns0,attr,omitempty"`

	Criteres *CriteresType `xml:"criteres,omitempty" json:"criteres,omitempty"`

	LoginUtilisateur *UtilisateurLoginType `xml:"loginUtilisateur,omitempty" json:"loginUtilisateur,omitempty"`
}

type RechercherPointResponseType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/services/rechercherpoint/v2.0 rechercherPointResponse"`

	Points *PointsType `xml:"points,omitempty" json:"points,omitempty"`
}

type PointsType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/services/rechercherpoint/v2.0 points"`

	Point *PointType `xml:"point,omitempty" json:"point,omitempty"`
}

type PointType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/services/rechercherpoint/v2.0 point"`

	AdresseInstallationNormalisee *AdresseAfnorType `xml:"adresseInstallationNormalisee,omitempty" json:"adresseInstallationNormalisee,omitempty"`

	Matricule *Chaine255Type `xml:"matricule,omitempty" json:"matricule,omitempty"`

	NumeroSerie *Chaine255Type `xml:"numeroSerie,omitempty" json:"numeroSerie,omitempty"`

	TypeComptage *StructureComptageType `xml:"typeComptage,omitempty" json:"typeComptage,omitempty"`

	EtatContractuel *PointEtatContractuelType `xml:"etatContractuel,omitempty" json:"etatContractuel,omitempty"`

	NomClientFinalOuDenominationSociale *Chaine255Type `xml:"nomClientFinalOuDenominationSociale,omitempty" json:"nomClientFinalOuDenominationSociale,omitempty"`

	Id *PointIdType `xml:"http://www.enedis.fr/sge/b2b/services/rechercherpoint/v2.0 id,attr,omitempty" json:"id,omitempty"`
}

type CriteresType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/services/rechercherpoint/v2.0 criteres"`

	AdresseInstallation *AdresseInstallationType `xml:"adresseInstallation,omitempty" json:"adresseInstallation,omitempty"`

	NumSiret *EtablissementNumSiretType `xml:"numSiret,omitempty" json:"numSiret,omitempty"`

	MatriculeOuNumeroSerie *Chaine255Type `xml:"matriculeOuNumeroSerie,omitempty" json:"matriculeOuNumeroSerie,omitempty"`

	DomaineTensionAlimentationCode *DomaineTensionCodeType `xml:"domaineTensionAlimentationCode,omitempty" json:"domaineTensionAlimentationCode,omitempty"`

	NomClientFinalOuDenominationSociale *Chaine255Type `xml:"nomClientFinalOuDenominationSociale,omitempty" json:"nomClientFinalOuDenominationSociale,omitempty"`

	CategorieClientFinalCode *ClientFinalCategorieCodeType `xml:"categorieClientFinalCode,omitempty" json:"categorieClientFinalCode,omitempty"`

	RechercheHorsPerimetre bool `xml:"rechercheHorsPerimetre,omitempty" json:"rechercheHorsPerimetre,omitempty"`
}

type AdresseInstallationType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/services/rechercherpoint/v2.0 adresseInstallation"`

	EscalierEtEtageEtAppartement *AdresseAfnorLigneType `xml:"escalierEtEtageEtAppartement,omitempty" json:"escalierEtEtageEtAppartement,omitempty"`

	Batiment *AdresseAfnorLigneType `xml:"batiment,omitempty" json:"batiment,omitempty"`

	NumeroEtNomVoie *AdresseAfnorLigneType `xml:"numeroEtNomVoie,omitempty" json:"numeroEtNomVoie,omitempty"`

	LieuDit *AdresseAfnorLigneType `xml:"lieuDit,omitempty" json:"lieuDit,omitempty"`

	CodePostal *CodePostalFrancaisType `xml:"codePostal,omitempty" json:"codePostal,omitempty"`

	CodeInseeCommune *CommuneFranceCodeInseeType `xml:"codeInseeCommune,omitempty" json:"codeInseeCommune,omitempty"`
}

//
// 'encodingStyle' indicates any canonicalization conventions followed in the contents of the containing element.  For example, the value 'http://schemas.xmlsoap.org/soap/encoding/' indicates the pattern described in SOAP specification
//

type EncodingStyle []AnyURI

type Envelope struct {
	Header *Header `xml:"Header,omitempty" json:"Header,omitempty"`

	Body *Body `xml:"Body,omitempty" json:"Body,omitempty"`

	Items []string `xml:",any" json:"items,omitempty"`
}

type Header struct {
	Items []string `xml:",any" json:"items,omitempty"`
}

type Body struct {
	Items []string `xml:",any" json:"items,omitempty"`
}

type Fault struct {
	Faultcode string `xml:"faultcode,omitempty" json:"faultcode,omitempty"`

	Faultstring string `xml:"faultstring,omitempty" json:"faultstring,omitempty"`

	Faultactor AnyURI `xml:"faultactor,omitempty" json:"faultactor,omitempty"`

	Detail *Detail `xml:"detail,omitempty" json:"detail,omitempty"`
}

type Detail struct {
	Items []string `xml:",any" json:"items,omitempty"`
}

type ResultatCodeType string

type ResultatLibelleType string

type VersionType string

type ErreurCommentaireType string

type DemandeurAdresseEmailType string

type DemandeurRefFrnType string

type DemandeurAppelIdType string

type ObjetIdType string

type Erreur ErreurType

type Acquittement AcquittementType

type Entete EnteteType

type AcquittementType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/technique/v1.0 acquittement"`

	Resultat *ResultatType `xml:"resultat,omitempty" json:"resultat,omitempty"`

	InfoFonctionnelles *InfoFonctionnellesType `xml:"infoFonctionnelles,omitempty" json:"infoFonctionnelles,omitempty"`

	InfoDemandeur *InfoDemandeurType `xml:"infoDemandeur,omitempty" json:"infoDemandeur,omitempty"`
}

type ResultatType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/technique/v1.0 resultat"`

	Value *ResultatLibelleType `xml:",chardata" json:"-,"`

	Code *ResultatCodeType `xml:"http://www.enedis.fr/sge/b2b/technique/v1.0 code,attr,omitempty" json:"code,omitempty"`
}

type ErreurType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/technique/v1.0 erreur"`

	Resultat *ResultatType `xml:"resultat,omitempty" json:"resultat,omitempty"`

	InfoFonctionnelles *InfoFonctionnellesType `xml:"infoFonctionnelles,omitempty" json:"infoFonctionnelles,omitempty"`

	InfoDemandeur *InfoDemandeurType `xml:"infoDemandeur,omitempty" json:"infoDemandeur,omitempty"`

	Commentaire *ErreurCommentaireType `xml:"commentaire,omitempty" json:"commentaire,omitempty"`
}

type EnteteType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/technique/v1.0 entete"`

	Version *VersionType `xml:"version,omitempty" json:"version,omitempty"`

	InfoFonctionnelles *InfoFonctionnellesType `xml:"infoFonctionnelles,omitempty" json:"infoFonctionnelles,omitempty"`

	InfoDemandeur *InfoDemandeurType `xml:"infoDemandeur,omitempty" json:"infoDemandeur,omitempty"`

	MustUnderstand bool `xml:"http://www.enedis.fr/sge/b2b/technique/v1.0 mustUnderstand,attr,omitempty" json:"mustUnderstand,omitempty"`
}

type InfoDemandeurType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/technique/v1.0 infoDemandeur"`

	LoginDemandeur *DemandeurAdresseEmailType `xml:"loginDemandeur,omitempty" json:"loginDemandeur,omitempty"`

	AppelDemandeurId *DemandeurAppelIdType `xml:"appelDemandeurId,omitempty" json:"appelDemandeurId,omitempty"`

	ReferenceDemandeur *DemandeurRefFrnType `xml:"referenceDemandeur,omitempty" json:"referenceDemandeur,omitempty"`

	ReferenceDemandeurGroupee *DemandeurRefFrnType `xml:"referenceDemandeurGroupee,omitempty" json:"referenceDemandeurGroupee,omitempty"`
}

type InfoFonctionnellesType struct {
	XMLName xml.Name `xml:"http://www.enedis.fr/sge/b2b/technique/v1.0 infoFonctionnelles"`

	PointId *ObjetIdType `xml:"pointId,omitempty" json:"pointId,omitempty"`

	AffaireId *ObjetIdType `xml:"affaireId,omitempty" json:"affaireId,omitempty"`
}

type RecherchePointPortType interface {

	// Error can be either of the following types:
	//
	//   - erreur

	RechercherPoint(request *RechercherPointType) (*RechercherPointResponseType, error)

	RechercherPointContext(ctx context.Context, request *RechercherPointType) (*RechercherPointResponseType, error)
}

type recherchePointPortType struct {
	client *soap.Client
}

func NewRecherchePointPortType(client *soap.Client) RecherchePointPortType {
	return &recherchePointPortType{
		client: client,
	}
}

func (service *recherchePointPortType) RechercherPointContext(ctx context.Context, request *RechercherPointType) (*RechercherPointResponseType, error) {
	response := new(RechercherPointResponseType)
	err := service.client.CallContext(ctx, "''", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *recherchePointPortType) RechercherPoint(request *RechercherPointType) (*RechercherPointResponseType, error) {
	return service.RechercherPointContext(
		context.Background(),
		request,
	)
}
